# Generated by Django 6.0.1 on 2026-01-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Rasm')),
                ('years_experience', models.IntegerField(verbose_name='Tajriba yillari')),
                ('happy_clients', models.IntegerField(verbose_name='Mamnun mijozlar')),
                ('destinations', models.IntegerField(verbose_name="Yo'nalishlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Pastki sarlavha')),
                ('background_image', models.ImageField(upload_to='banners/', verbose_name='Orqa fon rasm')),
                ('button1_text', models.CharField(max_length=50, verbose_name='1-tugma matni')),
                ('button1_link', models.CharField(max_length=100, verbose_name='1-tugma havolasi')),
                ('button2_text', models.CharField(blank=True, max_length=50, verbose_name='2-tugma matni')),
                ('button2_link', models.CharField(blank=True, max_length=100, verbose_name='2-tugma havolasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Kompaniya nomi')),
                ('company_subtitle', models.CharField(max_length=200, verbose_name='Kompaniya taglavhasi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('telegram_admin', models.CharField(max_length=100, verbose_name='Telegram admin')),
                ('telegram_channel', models.URLField(verbose_name='Telegram kanal')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('youtube', models.URLField(verbose_name='YouTube')),
                ('license_number', models.CharField(max_length=50, verbose_name='Litsenziya raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Kontakt ma'lumotlari",
                'verbose_name_plural': "Kontakt ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('flight', models.CharField(blank=True, max_length=100, verbose_name='Tanlangan parvoz')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('completed', 'Yakunlangan'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Parvoz nomi')),
                ('flight_type', models.CharField(choices=[('umra', 'Umra Safari'), ('haj', 'Haj Safari'), ('tour', 'Turistik Safari'), ('other', 'Boshqa')], default='tour', max_length=20, verbose_name='Parvoz turi')),
                ('date', models.DateField(verbose_name='Parvoz sanasi')),
                ('route_from', models.CharField(max_length=100, verbose_name='Qayerdan')),
                ('route_to', models.CharField(max_length=100, verbose_name='Qayerga')),
                ('available_seats', models.IntegerField(verbose_name='Qolgan joylar soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi ($)')),
                ('airline', models.CharField(max_length=100, verbose_name='Aviakompaniya')),
                ('departure_time', models.TimeField(verbose_name="Jo'nash vaqti")),
                ('arrival_time', models.TimeField(verbose_name='Yetib borish vaqti')),
                ('duration', models.CharField(max_length=50, verbose_name='Parvoz davomiyligi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('features', models.TextField(help_text='Har bir xizmat yangi qatordan yozilsin', verbose_name="Xizmatlar ro'yxati")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parvoz',
                'verbose_name_plural': 'Parvozlar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('service_type', models.CharField(choices=[('umra', 'Umra Safari'), ('haj', 'Haj Safari'), ('tour', 'Turistik Safari'), ('visa', 'Visa Xizmatlari')], max_length=20, verbose_name='Xizmat turi')),
                ('icon_class', models.CharField(default='fas fa-globe', max_length=50, verbose_name='Icon class (FontAwesome)')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Hudud/Mintaqa')),
                ('number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='main.contactinfo')),
            ],
            options={
                'verbose_name': 'Telefon raqami',
                'verbose_name_plural': 'Telefon raqamlari',
                'ordering': ['order'],
            },
        ),
    ]
