# Generated by Django 6.0.1 on 2026-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact_info',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='route_from',
            new_name='from_city',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='route_to',
            new_name='to_city',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='happy_clients',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='years_experience',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button1_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button1_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button2_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button2_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='features',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_type',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='clients',
            field=models.IntegerField(default=5000, verbose_name='Mamnun mijozlar'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='years',
            field=models.IntegerField(default=10, verbose_name='Tajriba yillari'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='flight_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tanlangan parvoz'),
        ),
        migrations.AddField(
            model_name='flight',
            name='services',
            field=models.TextField(blank=True, help_text='Har bir xizmat yangi qatordan yozilsin', verbose_name="Xizmatlar ro'yxati"),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fas fa-globe', help_text='FontAwesome icon: fas fa-kaaba, fas fa-mosque', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Xizmat nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='destinations',
            field=models.IntegerField(default=25, verbose_name="Yo'nalishlar soni"),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(verbose_name='Banner matni'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Banner sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aviakompaniya'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yetib borish vaqti'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(default=10, verbose_name='Qolgan joylar soni'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(blank=True, max_length=50, verbose_name="Jo'nash vaqti"),
        ),
        migrations.AlterField(
            model_name='flight',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Parvoz davomiyligi'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=930, verbose_name='Narxi ($)'),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
