# Generated by Django 6.0.1 on 2026-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_phonenumber_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('clients', models.PositiveIntegerField(default=0)),
                ('destinations', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='flight_info',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='services',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='flight',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='FontAwesome icon class (masalan: fas fa-kaaba)', max_length=50),
        ),
    ]
