# Generated by Django 6.0.1 on 2026-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_delete_aboutus_delete_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='to_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
