# Generated by Django 6.0.1 on 2026-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_flight_route_flight_airline_flight_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_city',
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='description',
            field=models.TextField(),
        ),
    ]
