# Generated by Django 6.0.1 on 2026-01-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_flight_airline_remove_flight_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date'], 'verbose_name': 'Parvoz', 'verbose_name_plural': 'Parvozlar'},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aviakompaniya'),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parvoz vaqti'),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_city',
            field=models.CharField(default=1, max_length=100, verbose_name='Qayerdan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='to_city',
            field=models.CharField(default=1, max_length=100, verbose_name='Qayerga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.PositiveIntegerField(verbose_name='Qolgan joylar'),
        ),
    ]
